### ISSUE TITLE
Face Recognition Library on Buildroot

### ISSUE THREAD

**Issue by varun2506** [cu-ecen-aeld/final-project-saloni1307#11]
Hello! 
We are trying to run our python application of facial recognition on Buildroot, and we are looking for help. I see that you implemented facial recognition in your project. I am not sure how to import face recognition libraries in Buildroot. I tried using the same packages you used, but the link seems to be broken. How did you achieve this?

**Comment by dwalkes** [comment]
@saloni1307 can you provide some advice?

**Comment by tanmay-mk** [comment]
Also, according to @dwalkes 's suggestion, we tried running your entire project on our system. However, we have been facing few issues. 
1. I see that you have used few legacy packages that are now blocking our build. 
![Legacy detected](https://user-images.githubusercontent.com/89433097/163727148-afb4283f-581f-4e3b-b07b-657654d32446.png)
![Legacy package](https://user-images.githubusercontent.com/89433097/163727153-6f809c95-efb6-4045-be07-67be7ace2db3.png)
![legacy terminal output](https://user-images.githubusercontent.com/89433097/163727156-a87e20b9-354b-4eca-90f0-f965e818eb1e.png)

2. Even after we remove this legacy package, we are getting this error on our build. 
![Dependencies issue](https://user-images.githubusercontent.com/89433097/163727165-1c39e4da-10b7-4f63-a810-19f1b92a7e56.png)

**Comment by saloni1307** [comment]
I never really ran into this issue of legacy options. As the build suggests, try deleting the config file and save again. I would suggest you go through all my previous issues also regarding installing dependency packages for face recognition, compare the config files for every package and also for linux config.

**Comment by saloni1307** [comment]
For the link of package in .mk file that you previously mentioned, please try [this link](https://files.pythonhosted.org/packages/6c/49/75dda409b94841f01cbbc34114c9b67ec618265084e4d12d37ab838f4fd3). Also check the hashes from [here](https://pypi.org/project/face-recognition/1.3.0/#copy-hash-modal-a76874c3-2c86-425c-b27f-42a73497a09e). You cannot access the python package link of pythonhosted.org from browser. You can find this link from their pypi website (Right click and copy link of the downloadable file given)

**Comment by tanmay-mk** [comment]
Can you please let me know which packages are required for facial recognition?
I installed 
1. dlib
2. pyparsing
3. python-face-recognition-models
4. python-face-recognition
5. python-scikit-build
as shown [here](https://github.com/cu-ecen-aeld/final-project-saloni1307/tree/master/base_external/package).

After installing these packages and building the image, I am getting this error: 
![image](https://user-images.githubusercontent.com/89433097/163837759-466e965f-21cc-44ae-af95-1c329db1c97f.png)

**Comment by tanmay-mk** [comment]
@dwalkes helped us recognize what the problem was. Apparently, all the packages were installed but even then buildroot was not showing all the packages. Cleaning and rebuilding python3 helped. We followed the following steps:

**(Inside your assignment repository)**
`cd buildroot`
`make python3-dirclean`
`make python3-rebuild`

After performing these steps, all python3 packages will be removed completely and rebuilt by buildroot.

**Comment by tanmay-mk** [comment]
After doing [these](https://github.com/cu-ecen-aeld/final-project-Amey2904dash/issues/8#issuecomment-1106215124) steps, we saved the buildroot configuration using [save_config.sh](https://github.com/cu-ecen-aeld/final-project-varun2506/blob/main/save_config.sh), and built a new buildroot image using [build.sh](https://github.com/cu-ecen-aeld/final-project-varun2506/blob/main/build.sh).

**Comment by tanmay-mk** [comment]
Successfully implemented the facial recognition code on Buildroot. 
![face rec update](https://user-images.githubusercontent.com/89433097/164675996-613a0678-d685-4a79-a8bd-8ce30094f25e.png)

**Comment by varun2506** [comment]
The issue was resolved. 
Issue Link: https://github.com/cu-ecen-aeld/final-project-tanmay-mk/issues/3
