### ISSUE TITLE
Python packages installation error on host

### ISSUE THREAD

**Issue by saloni1307** [cu-ecen-aeld/final-project-saloni1307#3]
python-dlib package requires 32-bit python. 
python3.8 32-bit installed using "sudo apt-get install python3.8:i386"
python2.7 32-bit not getting installed successfully. 
build.sh required 'hg' package to run, but this package gets deleted when installing 32-bit python.
Hence, build.sh completes with error due to absence of mercurial package.

**Comment by saloni1307** [comment]
This issue has been blocked by https://github.com/cu-ecen-aeld/final-project-saloni1307/issues/4

**Comment by saloni1307** [comment]
Blocker https://github.com/cu-ecen-aeld/final-project-saloni1307/issues/4 has been resolved. 
See details in comments in the issue.
Current working commit is https://github.com/cu-ecen-aeld/final-project-saloni1307/commit/5a76fa2b442caf791773fc4996b4ef9bf51667e1

**Comment by saloni1307** [comment]
Getting the following error while installing python-dlib package into my image from my host.

```
Building extension for Python 3.8.6 (default, Nov 13 2021, 23:12:19) 
Invoking CMake setup: 'cmake /home/saloni/final-project-saloni1307/buildroot/output/build/python-dlib-19.22.1/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/saloni/final-project-saloni1307/buildroot/output/build/python-dlib-19.22.1/build/lib.linux-x86_64-3.8 -DPYTHON_EXECUTABLE=/home/saloni/final-project-saloni1307/buildroot/output/host/bin/python -DCMAKE_BUILD_TYPE=Release'
CMake Error at /home/saloni/final-project-saloni1307/buildroot/output/build/python-dlib-19.22.1/dlib/external/pybind11/tools/FindPythonLibsNew.cmake:124 (message):
  Python config failure: Python is 64-bit, chosen compiler is 32-bit
Call Stack (most recent call first):
  /home/saloni/final-project-saloni1307/buildroot/output/build/python-dlib-19.22.1/dlib/external/pybind11/tools/pybind11Tools.cmake:16 (find_package)
  /home/saloni/final-project-saloni1307/buildroot/output/build/python-dlib-19.22.1/dlib/external/pybind11/CMakeLists.txt:33 (include)


-- Configuring incomplete, errors occurred!
See also "/home/saloni/final-project-saloni1307/buildroot/output/build/python-dlib-19.22.1/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 222, in <module>
    setup(
  File "/home/saloni/final-project-saloni1307/buildroot/output/host/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/saloni/final-project-saloni1307/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/saloni/final-project-saloni1307/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/saloni/final-project-saloni1307/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/saloni/final-project-saloni1307/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/saloni/final-project-saloni1307/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/saloni/final-project-saloni1307/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 134, in run
    self.build_extension(ext)
  File "setup.py", line 171, in build_extension
    subprocess.check_call(cmake_setup, cwd=build_folder)
  File "/home/saloni/final-project-saloni1307/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/saloni/final-project-saloni1307/buildroot/output/build/python-dlib-19.22.1/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/saloni/final-project-saloni1307/buildroot/output/build/python-dlib-19.22.1/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/home/saloni/final-project-saloni1307/buildroot/output/host/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
make[1]: *** [package/pkg-generic.mk:269: /home/saloni/final-project-saloni1307/buildroot/output/build/python-dlib-19.22.1/.stamp_built] Error 1
make: *** [Makefile:84: _all] Error 2
make: Leaving directory '/home/saloni/final-project-saloni1307/buildroot'

**Comment by saloni1307** [comment]
The main error here is 
```
Python config failure: Python is 64-bit, chosen compiler is 32-bit
```
According to this error, python version is 64-bit but we need 32-bit.
For that, I installed the 32-bit python version using following commands.
```
sudo apt-get install python3.8-minimal:i386
sudo apt-get install python3.8:i386
```
These commands installed python 32-bit. Even after that, I am getting the same error.

The python version can be checked using following command
```
python3 -c "import sys; print(sys.maxsize > 2**32)"
```
Output *True* means python version is 64-bit. Otherwise it is 32-bit.

***These commands change the image configuration of host (in this case ubuntu) in virtual machine. It then only boots in console mode. Do not repeat these steps.***

**Comment by saloni1307** [comment]
The python-dlib package also has CMake dependencies.
Currently I have installed cmake 3.15.5 in my buildroot, but I am getting the following error in my buildroot when I try to do pip3 install dlib.

![image](https://user-images.githubusercontent.com/77704335/141692351-0b2ccffa-8cc6-46d3-ab64-35ffa1c00bfa.png)

**Comment by saloni1307** [comment]
To solve this error I tried to install cmake 3.21.4. But that version is not getting installed on my host when doing build.sh. It gives the following error. 
```
indexerror: list index out of range
```
This error occurs when we try to access an element in a particular array which is either not indexed or the element indexed does not exist.
The rootcause for this error in this case is still unknown.

**Comment by saloni1307** [comment]
Faced this issue https://github.com/cu-ecen-aeld/final-project-saloni1307/issues/4 again.
Solved by restoring previous snapshot.
Built again.

**Comment by saloni1307** [comment]
Plan of action to get all required libraries installed in buildroot.
- Manually download or add (using sftp) tar file downloaded for the library in buildroot image
- Extract downloaded library
- Install the module

**Comment by saloni1307** [comment]
Documented steps for https://github.com/cu-ecen-aeld/final-project-saloni1307/issues/3#issuecomment-968369464

1. Download cmake
- wget https://github.com/Kitware/CMake/releases/download/v3.21.4/cmake-3.21.4.tar.gz
OR
- sftp https://github.com/Kitware/CMake/releases/download/v3.21.4/cmake-3.21.4.tar.gz

- tar x -vf cmake-3.21.4.tar.gz
- cd cmake-3.21.4
- ./configure --prefix=/opt/cmake
- make
- make install
- ./configure --prefix=/opt/cmake

**Not yet successful**

**Comment by saloni1307** [comment]
CMake .tar.gz extraction successful.
Getting the following error while configuring cmake

![image](https://user-images.githubusercontent.com/77704335/141705453-02d04281-dfe3-47a5-9a59-5593a5725cf4.png)

**Comment by saloni1307** [comment]
Blocked by https://github.com/cu-ecen-aeld/final-project-saloni1307/issues/5

**Comment by saloni1307** [comment]
Blocker removed

**Comment by saloni1307** [comment]
Tried to install wget for python using 
```
pip3 install python3-wget
```
wget was installed successfully
![image](https://user-images.githubusercontent.com/77704335/141711859-9f0ce897-5ce1-4d16-b6b1-0017a60de5de.png)

**Comment by saloni1307** [comment]
Tried to install cmake using python-wget but came across following error
![image](https://user-images.githubusercontent.com/77704335/141711997-d9f73488-d811-4a32-9d48-9194bcc273d0.png)

**Comment by saloni1307** [comment]
Changed buildroot build toolchain to glibc and gcc version to 8.x to accomodate opencv and numpy in buildroot image.
Ran clean-build again.

**Comment by saloni1307** [comment]
OpenCV and numpy packages imported in buildroot.

**Comment by saloni1307** [comment]
Successfully installed dlib package.
- Installed this recipe: https://github.com/cu-ecen-aeld/buildroot/tree/package-dlib/package/dlib
- Made changes in /home/saloni/final-project-saloni1307/buildroot/output/build/dlib-v19.17/dlib/external/pybind11/tools/FindPythonLibsNew.cmake file using this reference: https://github.com/cu-ecen-aeld/buildroot/blob/package-dlib/package/dlib/0001-pybind11-cmake-ignore-the-check-between-host-python-.patch
- Commit id: https://github.com/cu-ecen-aeld/final-project-saloni1307/commit/132411870fc7390d1d14d2656beeb8516614b53d

**Comment by saloni1307** [comment]
Successfully installed face_recognition package using 
```
pip3 install face_recognition
```

Also successfully built and installed recipe for face_recognition in buildroot image: https://github.com/cu-ecen-aeld/final-project-saloni1307/commit/6ab1f56eb49a07ecdffbcf179ffea8ef12340de0

**Comment by saloni1307** [comment]
Error in installing eye-game package using pip3 install

![image](https://user-images.githubusercontent.com/77704335/142747905-aa6bd246-eb5a-47c1-a7d2-ed38a74f64ff.png)

**Comment by saloni1307** [comment]
Installed and built packages pyparsing, packaging, wheel, distro and scikit-build which are dependencies for opencv-python which is a dependency of eye-game

scikit-build successful commit : https://github.com/cu-ecen-aeld/final-project-saloni1307/commit/96644cae22c69c24b419d0ec5d8ec9f00c406129

Other dependencies successful commit : https://github.com/cu-ecen-aeld/final-project-saloni1307/commit/ac13ec7c650e874fdb8176bdb7121baa33ac2072

**Comment by saloni1307** [comment]
Trying to build and install opencv-python package in buildroot. Getting following error while building the package.

![image](https://user-images.githubusercontent.com/77704335/142747930-c8f05120-04e4-4230-aa24-7f0c0a6e4c6b.png)

**Comment by saloni1307** [comment]
Added python-obd, face-recognition, face-recognition-models, opencv-python, packaging and scikit-build using utils/scanpypi. Build recipes no longer required. Getting error while installing wheel, distro and eye-game packages

Reference for scanpypi: https://buildroot.org/downloads/manual/manual.html#_infrastructure_for_python_packages

Commit: https://github.com/cu-ecen-aeld/final-project-saloni1307/commit/3a944c5dedf0d4a6ddaa462745372d823f4ac5cf

**Comment by saloni1307** [comment]
All packages required for face_recognition installed successfully. Face recognition working correctly on buildroot.

Commit: https://github.com/cu-ecen-aeld/final-project-saloni1307/commit/e79cd69a211c555f27bf65d0fa7fd99e91260972

**Comment by tanmay-mk** [comment]
https://github.com/cu-ecen-aeld/final-project-saloni1307/issues/3#issuecomment-968334781

No need to perform these steps. When you get [this](https://github.com/cu-ecen-aeld/final-project-saloni1307/issues/3#issuecomment-968335697) error, just perform [these](https://github.com/cu-ecen-aeld/final-project-saloni1307/issues/3#issuecomment-969698149) steps.
